In [1]:
import json
import pandas as pd
import numpy as np
from pathlib import Path
from datetime import datetime

In [2]:
bronze_path = Path.cwd()/"data"/"bronze"

file_name = "tfl-bikes-2026-07-24-H12-M45.json"

if ((file_name[:10]+file_name[-5:])!="tfl-bikes-.json"):
    print(f"Formatting error using {file_name}")
    raise ValueError
else:
    time = (file_name[10:-5])
    date_time = datetime.strptime(
        time,
        "%Y-%m-%d-H%H-M%M"
    )
    print(date_time)

with open(bronze_path/file_name) as f:
    json_input = json.load(f)

df = pd.json_normalize(json_input)
df["date_time"] = date_time

2026-07-24 12:45:00

In [3]:
df_long = df.explode("additionalProperties", True)
df_long

,$type,id,url,commonName,placeType,additionalProperties,children,childrenUrls,lat,lon,date_time
0,"Tfl.Api.Presentation.Entities.Place, Tfl.Api.P...",BikePoints_1,/Place/BikePoints_1,"River Street , Clerkenwell",BikePoint,{'$type': 'Tfl.Api.Presentation.Entities.Addit...,[],[],51.529163,-0.109970,2026-07-24 12:45:00
1,"Tfl.Api.Presentation.Entities.Place, Tfl.Api.P...",BikePoints_1,/Place/BikePoints_1,"River Street , Clerkenwell",BikePoint,{'$type': 'Tfl.Api.Presentation.Entities.Addit...,[],[],51.529163,-0.109970,2026-07-24 12:45:00
2,"Tfl.Api.Presentation.Entities.Place, Tfl.Api.P...",BikePoints_1,/Place/BikePoints_1,"River Street , Clerkenwell",BikePoint,{'$type': 'Tfl.Api.Presentation.Entities.Addit...,[],[],51.529163,-0.109970,2026-07-24 12:45:00
3,"Tfl.Api.Presentation.Entities.Place, Tfl.Api.P...",BikePoints_1,/Place/BikePoints_1,"River Street , Clerkenwell",BikePoint,{'$type': 'Tfl.Api.Presentation.Entities.Addit...,[],[],51.529163,-0.109970,2026-07-24 12:45:00
4,"Tfl.Api.Presentation.Entities.Place, Tfl.Api.P...",BikePoints_1,/Place/BikePoints_1,"River Street , Clerkenwell",BikePoint,{'$type': 'Tfl.Api.Presentation.Entities.Addit...,[],[],51.529163,-0.109970,2026-07-24 12:45:00
...,...,...,...,...,...,...,...,...,...,...,...
8773,"Tfl.Api.Presentation.Entities.Place, Tfl.Api.P...",BikePoints_751,/Place/BikePoints_751,"Newton Street, Covent Garden",BikePoint,{'$type': 'Tfl.Api.Presentation.Entities.Addit...,[],[],51.516128,-0.120909,2026-07-24 12:45:00
8774,"Tfl.Api.Presentation.Entities.Place, Tfl.Api.P...",BikePoints_751,/Place/BikePoints_751,"Newton Street, Covent Garden",BikePoint,{'$type': 'Tfl.Api.Presentation.Entities.Addit...,[],[],51.516128,-0.120909,2026-07-24 12:45:00
8775,"Tfl.Api.Presentation.Entities.Place, Tfl.Api.P...",BikePoints_751,/Place/BikePoints_751,"Newton Street, Covent Garden",BikePoint,{'$type': 'Tfl.Api.Presentation.Entities.Addit...,[],[],51.516128,-0.120909,2026-07-24 12:45:00
8776,"Tfl.Api.Presentation.Entities.Place, Tfl.Api.P...",BikePoints_751,/Place/BikePoints_751,"Newton Street, Covent Garden",BikePoint,{'$type': 'Tfl.Api.Presentation.Entities.Addit...,[],[],51.516128,-0.120909,2026-07-24 12:45:00
8777,"Tfl.Api.Presentation.Entities.Place, Tfl.Api.P...",BikePoints_751,/Place/BikePoints_751,"Newton Street, Covent Garden",BikePoint,{'$type': 'Tfl.Api.Presentation.Entities.Addit...,[],[],51.516128,-0.120909,2026-07-24 12:45:00

In [4]:
properties = pd.json_normalize(
    df_long["additionalProperties"]
)

In [5]:
properties

,$type,category,key,sourceSystemKey,value,modified
0,Tfl.Api.Presentation.Entities.AdditionalProper...,Description,TerminalName,BikePoints,001023,2026-07-24T12:43:59.477Z
1,Tfl.Api.Presentation.Entities.AdditionalProper...,Description,Installed,BikePoints,true,2026-07-24T12:43:59.477Z
2,Tfl.Api.Presentation.Entities.AdditionalProper...,Description,Locked,BikePoints,false,2026-07-24T12:43:59.477Z
3,Tfl.Api.Presentation.Entities.AdditionalProper...,Description,InstallDate,BikePoints,1278947280000,2026-07-24T12:43:59.477Z
4,Tfl.Api.Presentation.Entities.AdditionalProper...,Description,RemovalDate,BikePoints,,2026-07-24T12:43:59.477Z
...,...,...,...,...,...,...
8773,Tfl.Api.Presentation.Entities.AdditionalProper...,Description,NbBikes,BikePoints,12,2026-07-24T12:43:59.477Z
8774,Tfl.Api.Presentation.Entities.AdditionalProper...,Description,NbEmptyDocks,BikePoints,10,2026-07-24T12:43:59.477Z
8775,Tfl.Api.Presentation.Entities.AdditionalProper...,Description,NbDocks,BikePoints,24,2026-07-24T12:43:59.477Z
8776,Tfl.Api.Presentation.Entities.AdditionalProper...,Description,NbStandardBikes,BikePoints,5,2026-07-24T12:43:59.477Z
8777,Tfl.Api.Presentation.Entities.AdditionalProper...,Description,NbEBikes,BikePoints,7,2026-07-24T12:43:59.477Z

In [6]:
dfx = pd.concat(
    [
        df_long[["id", "date_time"]],
        properties
    ],
    axis=1
)

In [7]:
dfx_filtered = dfx[["id", "date_time", "key", "value"]]
dfx_filtered

                  id           date_time              key          value
0       BikePoints_1 2026-07-24 12:45:00     TerminalName         001023
1       BikePoints_1 2026-07-24 12:45:00        Installed           true
2       BikePoints_1 2026-07-24 12:45:00           Locked          false
3       BikePoints_1 2026-07-24 12:45:00      InstallDate  1278947280000
4       BikePoints_1 2026-07-24 12:45:00      RemovalDate
...              ...                 ...              ...            ...
8773  BikePoints_751 2026-07-24 12:45:00          NbBikes             12
8774  BikePoints_751 2026-07-24 12:45:00     NbEmptyDocks             10
8775  BikePoints_751 2026-07-24 12:45:00          NbDocks             24
8776  BikePoints_751 2026-07-24 12:45:00  NbStandardBikes              5
8777  BikePoints_751 2026-07-24 12:45:00         NbEBikes              7

[8778 rows x 4 columns]

In [8]:
dfx_filtered["key"].unique()

array(['TerminalName', 'Installed', 'Locked', 'InstallDate',
       'RemovalDate', 'Temporary', 'NbBikes', 'NbEmptyDocks', 'NbDocks',
       'NbStandardBikes', 'NbEBikes'], dtype=object)

In [9]:
wanted = dfx_filtered["key"].unique()[6:11]

In [10]:
dfx_filtered

                  id           date_time              key          value
0       BikePoints_1 2026-07-24 12:45:00     TerminalName         001023
1       BikePoints_1 2026-07-24 12:45:00        Installed           true
2       BikePoints_1 2026-07-24 12:45:00           Locked          false
3       BikePoints_1 2026-07-24 12:45:00      InstallDate  1278947280000
4       BikePoints_1 2026-07-24 12:45:00      RemovalDate
...              ...                 ...              ...            ...
8773  BikePoints_751 2026-07-24 12:45:00          NbBikes             12
8774  BikePoints_751 2026-07-24 12:45:00     NbEmptyDocks             10
8775  BikePoints_751 2026-07-24 12:45:00          NbDocks             24
8776  BikePoints_751 2026-07-24 12:45:00  NbStandardBikes              5
8777  BikePoints_751 2026-07-24 12:45:00         NbEBikes              7

[8778 rows x 4 columns]

In [11]:
mask = dfx_filtered["key"].isin(wanted)

wanted_rows = dfx_filtered[mask]

wanted_rows#[["id", "key", "value"]]

                  id           date_time              key value
6       BikePoints_1 2026-07-24 12:45:00          NbBikes     2
7       BikePoints_1 2026-07-24 12:45:00     NbEmptyDocks    16
8       BikePoints_1 2026-07-24 12:45:00          NbDocks    19
9       BikePoints_1 2026-07-24 12:45:00  NbStandardBikes     1
10      BikePoints_1 2026-07-24 12:45:00         NbEBikes     1
...              ...                 ...              ...   ...
8773  BikePoints_751 2026-07-24 12:45:00          NbBikes    12
8774  BikePoints_751 2026-07-24 12:45:00     NbEmptyDocks    10
8775  BikePoints_751 2026-07-24 12:45:00          NbDocks    24
8776  BikePoints_751 2026-07-24 12:45:00  NbStandardBikes     5
8777  BikePoints_751 2026-07-24 12:45:00         NbEBikes     7

[3990 rows x 4 columns]

In [12]:
wanted_rows.columns

Index(['id', 'date_time', 'key', 'value'], dtype='object')

In [14]:
df_pivot = dfx_filtered.pivot(index=["id", "date_time"], columns="key", values="value")

new_mask = df_pivot.columns[3:8]
new_df = df_pivot[new_mask]
new_df

,key,NbBikes,NbDocks,NbEBikes,NbEmptyDocks,NbStandardBikes
id,date_time,,,,,
BikePoints_1,2026-07-24 12:45:00,2,19,1,16,1
BikePoints_10,2026-07-24 12:45:00,3,18,1,13,2
BikePoints_101,2026-07-24 12:45:00,20,22,3,2,17
BikePoints_102,2026-07-24 12:45:00,9,17,4,5,5
BikePoints_103,2026-07-24 12:45:00,2,18,1,15,1
...,...,...,...,...,...,...
BikePoints_94,2026-07-24 12:45:00,4,28,0,23,4
BikePoints_95,2026-07-24 12:45:00,8,15,2,5,6
BikePoints_96,2026-07-24 12:45:00,8,26,0,17,8
BikePoints_97,2026-07-24 12:45:00,10,18,0,6,10
BikePoints_98,2026-07-24 12:45:00,14,54,2,36,12